namespace VoiceBot.Application.Interfaces;

// ---------------------------------------------------------------------------
// Response record — lives here (Application) so VoiceOrchestrator can see it
// without depending on Infrastructure. Infrastructure implements the interface
// and produces instances of this record; the orchestrator consumes them.
// ---------------------------------------------------------------------------

/// <summary>
/// The unified response produced by any ILlmBackend implementation.
/// Using a record gives value-based equality and immutability for free.
/// </summary>
/// <param name="Transcript">STT transcript of the caller's audio.</param>
/// <param name="ResponseText">Natural-language reply generated by the LLM.</param>
/// <param name="AudioBase64">Base64-encoded TTS audio of the reply.</param>
/// <param name="AudioFormat">Audio codec, e.g. "mp3" or "wav".</param>
/// <param name="LatencyMs">
/// Per-stage latency in milliseconds, as reported by the backend.
/// Keys match the Python service: "stt", "db_fetch", "llm", "db_write", "tts", "total".
/// </param>
public record LlmBackendResponse(
    string Transcript,
    string ResponseText,
    string AudioBase64,
    string AudioFormat,
    Dictionary<string, int> LatencyMs
);

// ---------------------------------------------------------------------------
// Interface
// ---------------------------------------------------------------------------

/// <summary>
/// Abstraction over any voice-processing backend (Python pipeline, WhatsApp team, etc.).
///
/// Clean Architecture rule: this interface lives in Application, not Domain,
/// because it orchestrates infrastructure-level IO (HTTP calls).
/// Domain should remain free of any IO abstractions.
/// </summary>
public interface ILlmBackend
{
    /// <summary>
    /// Sends audio to the backend and returns the full pipeline response.
    /// </summary>
    /// <param name="sessionId">
    /// Conversation session identifier, generated by the orchestrator.
    /// Allows the backend to maintain multi-turn context per caller session.
    /// </param>
    /// <param name="audioBytes">Raw audio bytes captured from the caller.</param>
    /// <param name="audioFileName">
    /// Original filename (with extension) — lets the backend detect the audio codec.
    /// </param>
    /// <param name="ct">Propagates request cancellation from the HTTP pipeline.</param>
    Task<LlmBackendResponse> ProcessAsync(
        string sessionId,
        byte[] audioBytes,
        string audioFileName,
        CancellationToken ct = default);
}
